# This workflow will build a package using Maven and then publish it to GitHub packages when a release is created
# For more information see: https://github.com/actions/setup-java/blob/main/docs/advanced-usage.md#apache-maven-with-a-settings-path

name: Maven Package

on:
  push:
    branches:
      - main
      - 'ci/*'
  pull_request:
    branches:
      - main


jobs:

  integration-test:

    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 21
      uses: actions/setup-java@v3
      with:
        java-version: '21'
        distribution: 'temurin'
        server-id: github # Value of the distributionManagement/repository/id field of the pom.xml
        cache: 'maven'
    - name: Check Java version
      run: java -version

    - name: Build and run integration tests
      run: ./mvnw clean integration-test

      
  maven:

    runs-on: ubuntu-latest
    needs: integration-test
    permissions:
      contents: read
      packages: write

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 21
      uses: actions/setup-java@v3
      with:
        java-version: '21'
        distribution: 'temurin'
        server-id: github # Value of the distributionManagement/repository/id field of the pom.xml
        cache: 'maven'
    - name: Check Java version
      run: java -version

    - name: Build with Maven
      run: ./mvnw clean package verify

    - name: Upload artifact for Docker job
      uses: actions/upload-artifact@v3
      with:
        name: java-app
        path: '${{ github.workspace }}/target/*.jar' 

  docker:

    runs-on: ubuntu-latest
    needs: maven
    permissions:
      contents: read
      packages: write

    steps:
    - uses: actions/checkout@v4
    
    - name: Download artifact from maven job
      uses: actions/download-artifact@v3
      with:
        name: java-app

    - name: Logging in to Docker
      run: docker login ghcr.io -u aradidaniel -p ${{ github.token }} 
    
    - name: Build the Docker image
      run: docker build . -t ghcr.io/aradidaniel/cubix/1/optional/app:springboot
    
    - name: Publishing the Docker image
      run: docker push ghcr.io/aradidaniel/cubix/1/optional/app:springboot
